# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- ado-gcp-terraform

pool:
  name: TestAgentPool

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)/s/manifest-files'
    Contents: |
      **
      *.tf
    TargetFolder: '$(build.artifactstagingdirectory)'


- script: |
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'