
trigger:
- main

pool:
  name: TestAgentPool

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)/manifest-files'
    Contents: |
      **
      *.tf
    TargetFolder: '$(build.artifactstagingdirectory)'

- script: |
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
